# action.yml
name: 'Work wechat agent message send'
description: 'send message to wechat work'
inputs:
  wechat_id:
    description: 'wechat id'
    required: true
    default: ''
  agent_secret:
    description: 'agent secret'
    required: true
    default: ''
  agent_id:
    description: 'agent id'
    required: true
    default: ''
  to_user:
    description: 'user name list'
    required: false
    default: '@all'
  msgtype:
    description: 'msg type'
    required: false
    default: 'text'
  content:
    description: 'use \n for line break'
    required: true
    default: ''
  cache_path:
    description: 'token path'
    required: false
    default: '~/.wechat_token/'
  send_step:
    description: 'main or post'
    required: false
    default: 'main'
  mock:
    description: 'main or post'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.wechat_id }}
    - ${{ inputs.agent_secret }}
    - ${{ inputs.agent_id }}
    - ${{ inputs.to_user }}
    - ${{ inputs.msgtype }}
    - ${{ inputs.content }}
    - ${{ inputs.cache_path }}
    - ${{ inputs.send_step }}
    - ${{ inputs.mock }}
  entrypoint: '/opt/bin/main.sh'
  post-entrypoint: '/opt/bin/post.sh'
